baseURL = "https://hyzhu.com/"
languageCode = "en-us"
title = 'Sean Zhu Blog'
theme = "hugo-ht"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
enableGitInfo = true
enableRobotsTXT = true

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "Work"
    url = "/en/work/"
    weight = 2

# [[menu.en]]
#     name = "Research"
#     url = "/en/research/"
#     weight = 3

[[menu.en]]
    name = "Blog"
    url = "/en/blog/"
    weight = 4
[[menu.en]]
    name = "中文"
    url = "/cn/blog/"
    weight = 5
[[menu.cn]]
    name = "关于"
    url = "/cn/"
    weight = 1
[[menu.cn]]
    name = "日志"
    url = "/cn/blog/"
    weight = 2
[[menu.cn]]
    name = "English"
    url = "/"
    weight = 3

[params]
    description = "Peronal website of Sean Zhu"
    homeText = "Sean Zhu's Personal Website"
    blogDirName = "blog"
    singleLang = false
    defaultLang = "en"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    favicon = "/icon.jpg"
    copyright = "&copy;"
    copyrightYear = "2024"
    GithubEdit = "https://github.com/techhyz/techhyz.github.io/edit/sources/content/"
    GithubRepo = "https://github.com/techhyz/techhyz.github.io"
    ContentSource = "https://raw.githubusercontent.com/techhyz/techhyz.github.io/sources/content/"

[params.logo]
  url = "icon.jpg"
  alt = "Sean Zhu"

[params.lang]

    [params.lang.author]
      en = "Sean Zhu"
      cn = "Sean Zhu"

    [params.lang.poweredBy]
      en = "Made with"
      cn = "本站驱动"

    [params.lang.edit]
      en = "Suggest an edit of this page"
      cn = "编辑本页"

    [params.lang.lastupdate]
      en = "Last modified on"
      cn = "最后一次修改于"

    [params.lang.Sitelastupdate]
      en = "Site last updated on"
      cn = "最近一次更新于"

    [params.lang.subscribe]
      en = "Subscribe"
      cn = "订阅"

    [params.lang.sourceCode]
      en = "Content in"
      cn = "内容存于"

    [params.lang.license]
      en = "License"
      cn = "版权"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2

[imaging]
quality = 100

